[package]
name = "midi-synth"
version = "0.1.0"
authors = ["df5602 <dominik@fankhausers.ch>"]

[dependencies]
libusb = "*"
itertools = "*"
error-chain = "*"
lazy_static = "*"
portaudio = "*"
ctrlc = { version = "*", features = ["termination"] }